# These are supported funding model platforms

# github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
# patreon: # Replace with a single Patreon username
# open_collective: # Replace with a single Open Collective username
# ko_fi: # Replace with a single Ko-fi username
# tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
# liberapay: # Replace with a single Liberapay username
# issuehunt: # Replace with a single IssueHunt username
# lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# polar: # Replace with a single Polar username
# buy_me_a_coffee: # Replace with a single Buy Me a Coffee username
# custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
# # These are supported funding model platforms

github: [helloharendra,]
patreon: your-patreon-username
open_collective: your-open-collective-username
ko_fi: your-ko-fi-username
tidelift: platform-name/package-name
community_bridge: your-community-bridge-project-name
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
lfx_crowdfunding: your-lfx-crowdfunding-project-name
polar: your-polar-username
buy_me_a_coffee: your-buy-me-a-coffee-username
custom: ['helloharendra.github.io', 'https://tanyafinance.com/harendraprajapati/', ]
